package com.extc.entity;


// Generated 7 Jan, 2021 12:30:54 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Empolyeesdetails generated by hbm2java
 */
@Entity
@Table(name = "empolyeesdetails", catalog = "companydata")
public class Empolyeesdetails implements java.io.Serializable {

	private Integer srNo;
	private String name;
	private String contactNo;
	private String email;

	public Empolyeesdetails() {
	}

	public Empolyeesdetails(String name, String contactNo, String email) {
		this.name = name;
		this.contactNo = contactNo;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SrNo", unique = true, nullable = false)
	public Integer getSrNo() {
		return this.srNo;
	}

	public void setSrNo(Integer srNo) {
		this.srNo = srNo;
	}

	@Column(name = "Name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ContactNo", nullable = false, length = 45)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "Email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
