package com.extc.entity;
// default package
// Generated 7 Jan, 2021 12:30:54 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Managerdetails generated by hbm2java
 */
@Entity
@Table(name = "managerdetails", catalog = "companydata")
public class Managerdetails implements java.io.Serializable {

	private Integer srNo;
	private String name;
	private String email;
	private String contactNo;
	private String password;

	public Managerdetails() {
	}

	public Managerdetails(String name, String email, String contactNo, String password) {
		this.name = name;
		this.email = email;
		this.contactNo = contactNo;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SrNo", unique = true, nullable = false)
	public Integer getSrNo() {
		return this.srNo;
	}

	public void setSrNo(Integer srNo) {
		this.srNo = srNo;
	}

	@Column(name = "Name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ContactNo", nullable = false, length = 45)
	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	@Column(name = "Password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
